@port = 8080
@host = coteccons.info 
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhc3Npc3RhbnQtcHVibGljLWFwaSIsImV4cCI6IjIwMjQtMDEtMTBUMjM6NDc6MTUuMjg2MTQ1NTcxKzA3OjAwIiwidXNlcl9pZCI6MTR9.gs5Epes7Rmm-vGip8V3G169fdBH8DjhQE2pLvpvf5kQ
@task = private-tasks


###########
# AUTH #
###########
# Create
POST https://{{host}}/api/v1/auth HTTP/1.1
Content-Type: application/json
{{token}}
{"username":"manhdung@gmail.com","password":"123456"}
###

# Read list
GET https://{{host}}/api/v1/{{task}} HTTP/1.1
Content-Type: application/json
{{token}}
###