@port = 8080
@host = coteccons.info 
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhc3Npc3RhbnQtcHVibGljLWFwaSIsImV4cCI6IjIwMjQtMDEtMDJUMDE6MjM6NDAuODM1OTkzMDE0KzA3OjAwIiwidXNlcl9pZCI6Mn0.zA88KU5PhITf0r0KpZRCK235RPbnhdhuu_rsEsXzuNE
@task = tasks


###########
# AUTH #
###########
# Create
POST https://{{host}}/auth HTTP/1.1
Content-Type: application/json
{{token}}

{"username":"abc","password":"123456"}

############
# PROJECTS #
############
# CREATE

POST http://{{host}}/api/v1/{{task}} HTTP/1.1
Content-Type: application/json
{{token}}

{"name":"Test task 2", "project_id":13,"executor_id":6,"start_time":"2023-10-04","end_time":"2023-04-05","quantity":300,"price":20000,"description":"san tang 2","priority_level":"low"}

############
# USERS #
############
# UPDATE

PUT http://{{host}}/api/v1/{{task}}/17 HTTP/1.1
Content-Type: application/json
{{token}}

{
    "name": "Test task 01",
    "start_time": "2023-07-06",
    "end_time": "2023-07-31",
    "quantity": 10,
    "price": 1000000,
    "unit": "mm",
    "description": "note",
    "status": "created",
    "priority_level": "low"
  }
###

# Read
GET http://{{host}}/api/v1/{{task}}/17 HTTP/1.1
{{token}}
###

# Read list
GET http://{{host}}/api/v1/{{task}} HTTP/1.1
{{token}}
###

# Delete
DELETE http://{{host}}/api/v1/{{task}}/7 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
{{token}}
###
