@port = 8080
@host = coteccons.info
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhc3Npc3RhbnQtcHVibGljLWFwaSIsImV4cCI6IjIwMjQtMDItMTdUMjI6MTg6MzEuNDY2NTQ1NjEyKzA3OjAwIiwidXNlcl9pZCI6MTR9.I9EBTaWQxWPNg6XvB4IQ9GNN66JwdxOnQ0HabeKqju0
@user = users


###########
# AUTH #
###########
# Create
POST https://{{host}}/api/v1/auth HTTP/1.1
Content-Type: application/json
{{token}}

{"username":"manhdung@gmail.com","password":"123456"}

############
# AUTH #
############
# INFO #

GET https://{{host}}/api/v1/me HTTP/1.1
Content-Type: application/json
{{token}}

############
# PROJECTS #
############
# CREATE

POST http://{{host}}/api/v1/{{user}} HTTP/1.1
Content-Type: application/json
{{token}}

{"code":"NV002","name":"Nguyan Van B", "phone":"1234568","email":"nguyanvanb@abc.com"}

############
# USERS #
############
# UPDATE

PUT http://{{host}}/api/v1/{{user}}/3 HTTP/1.1
Content-Type: application/json
{{token}}

{"code":"NV002","name":"Nguyan Van B", "phone":"1234567","email":"nguyanvanb@abc.com"}
###

# Read
GET http://{{host}}/api/v1/{{user}}/3 HTTP/1.1
{{token}}
###

# Read
GET http://{{host}}/api/v1/{{user}} HTTP/1.1
{{token}}
###

# Delete
DELETE http://{{host}}/api/v1/{{user}}/3 HTTP/1.1
Content-Type: application/json
{{token}}
###
